application: service-discovery
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- channel_presence

handlers:
- url: /css
  static_dir: static/css
  expiration: 1h
- url: /js
  static_dir: static/js
  expiration: 1h
- url: /img
  static_dir: static/img
  expiration: 7d
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /work/import
  script: main.app
  login: admin
- url: /work/maintenance
  script: main.app
  login: admin
- url: /_ah/channel/connected/
  script: main.app
- url: /_ah/channel/disconnected/
  script: main.app
- url: .*
  script: main.app

builtins:
- deferred: on
- admin_redirect: on
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(console.py)

pagespeed:
  enabled_rewriters:
  - MinifyCss
  - CollapseWhitespace