application: service-discovery
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- channel_presence

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /favicon\.ico
  static_files: favicon.ico
  upload: static/favicon\.ico
- url: /work/import
  script: main.app
  login: admin
- url: /_ah/channel/connected/
  script: main.app
- url: /_ah/channel/disconnected/
  script: main.app
- url: .*
  script: main.app

builtins:
- deferred: on
- admin_redirect: on
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest